language: php

php:
  - 5.6
  - 7.0
  - 7.1

before_script:
  - mkdir config
  - cp tests/ci_bootstrap.php config/bootstrap.php
  - mkdir ../libraries
  - git clone --branch=1.1 --depth=100 --quiet git://github.com/UnionOfRAD/lithium.git ../libraries/lithium
  - git clone --branch=master --depth=100 --quiet git://github.com/UnionOfRAD/li3_fixtures.git ../libraries/li3_fixtures
  - mysql -e 'create database li3migrations_test;'

script: ../libraries/lithium/console/li3 test --filters=Profiler tests/cases